/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx.h"
#include "stm32f446xx_gpio.h"


void delay(uint32_t count)
{
    while(count--);
}

int main(void)
{
    GPIO_Handle_t GpioLed;

    GpioLed.pGPIOx = GPIOA;				//GPIO PORT A
    GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;	//PIN 5 of PORT A
    GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;		//PA5 as an OUTPUT
    GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;		//FAST speed
    GpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;		//NO pull-up and pull-down resistor
    GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

    GPIO_PeriClockControl(GPIOA, ENABLE);			//clk enable
    GPIO_Init(&GpioLed);

    uint8_t duty;

    while(1)
    {
        //Fade In
        for(duty = 0; duty <= 20; duty++)
        {
            for(uint16_t i = 0; i < 20; i++)
            {
                GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_5, SET);
                delay(duty * 80);

                GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_5, RESET);
                delay((100 - duty) * 80);
            }
        }

        //Fade Out
        for(duty = 20; duty > 0; duty--)
        {
            for(uint16_t i = 0; i < 100; i++)
            {
                GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_5, SET);
                delay(duty * 80);

                GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_5, RESET);
                delay((100 - duty) * 80);
            }
        }
    }
}
