/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx.h"
#include "stm32f446xx_gpio.h"

int main(void)
{
    GPIO_Handle_t GpioLed, GpioButton;

    /* LED : PA5 */
    GpioLed.pGPIOx = GPIOA;											//GPIO port A for the LED
    GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;			//PIN 5
    GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;			//PA5 o/p
    GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;			//output speed fast
    GpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;		//push-pull o/p
    GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;		// no pull-up

    GPIO_PeriClockControl(GPIOA, ENABLE);		//clk enable
    GPIO_Init(&GpioLed);

    /* Push Button : PC13 */
    GpioButton.pGPIOx = GPIOC;												//GPIO PORTC
    GpioButton.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;				//PC13 push button
    GpioButton.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;					//PC13 as an  INPUT
    GpioButton.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;				//input speed
    GpioButton.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU;			//enable pull-up resistor

    GPIO_PeriClockControl(GPIOC, ENABLE);
    GPIO_Init(&GpioButton);

    while(1)
    {
        if(GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_13) == RESET)
        {
            for(uint32_t i = 0; i < 200000; i++);
            GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_NO_5);

            while(GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_13) == RESET);
        }
    }
}
